#!/usr/bin/env sh
set -eu

REPOSITORY_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
EXPECTED_CARGO_ABOUT_VERSION=0.9.1
EXPECTED_WEBVIEW2_COM_SYS_VERSION=0.38.2
EXPECTED_RING_VERSION=0.17.14
EXPECTED_RING_CHECKSUM=a4689e6c2294d81e88dc6261c768b63bc4fcdb852be6d1352498b114f61383b7

cd "$REPOSITORY_DIR"

if ! command -v cargo-about >/dev/null 2>&1; then
  printf '%s\n' \
    "cargo-about $EXPECTED_CARGO_ABOUT_VERSION is required to verify third-party licenses." \
    "Install it with:" \
    "  cargo install cargo-about --version $EXPECTED_CARGO_ABOUT_VERSION --locked --features cli" >&2
  exit 1
fi

if [ "$(cargo about --version)" != "cargo-about $EXPECTED_CARGO_ABOUT_VERSION" ]; then
  printf 'cargo-about %s is required; found %s.\n' \
    "$EXPECTED_CARGO_ABOUT_VERSION" "$(cargo about --version)" >&2
  exit 1
fi

# webview2-com-sys packages Microsoft's prebuilt WebView2Loader static library,
# whose NuGet BSD-3 terms are separate from the crate's MIT metadata. Tie the
# checked-in native notice to the exact crate version that supplies that binary;
# a dependency update must explicitly review and refresh the SDK version/terms.
WEBVIEW2_COM_SYS_VERSION=$(
  awk '
    $0 == "name = \"webview2-com-sys\"" { found = 1; next }
    found && /^version = "/ {
      value = $0
      sub(/^version = "/, "", value)
      sub(/"$/, "", value)
      print value
      exit
    }
    found && /^\[\[package\]\]$/ { exit }
  ' Cargo.lock
)
if [ "$WEBVIEW2_COM_SYS_VERSION" != "$EXPECTED_WEBVIEW2_COM_SYS_VERSION" ]; then
  printf '%s\n' \
    "webview2-com-sys changed from $EXPECTED_WEBVIEW2_COM_SYS_VERSION to ${WEBVIEW2_COM_SYS_VERSION:-missing}." \
    'Review the bundled WebView2 SDK version and license, then update about.hbs and this check.' >&2
  exit 1
fi

# ring compiles several native C files whose per-file ISC notices are not all
# represented by the crate-level license generated by cargo-about. Pin both the
# version and crates.io archive checksum: any source change must explicitly
# re-review the native attributions embedded in about.hbs.
RING_VERSION=$(
  awk '
    $0 == "name = \"ring\"" { found = 1; next }
    found && /^version = "/ {
      value = $0
      sub(/^version = "/, "", value)
      sub(/"$/, "", value)
      print value
      exit
    }
    found && /^\[\[package\]\]$/ { exit }
  ' Cargo.lock
)
RING_CHECKSUM=$(
  awk '
    $0 == "name = \"ring\"" { found = 1; next }
    found && /^checksum = "/ {
      value = $0
      sub(/^checksum = "/, "", value)
      sub(/"$/, "", value)
      print value
      exit
    }
    found && /^\[\[package\]\]$/ { exit }
  ' Cargo.lock
)
if [ "$RING_VERSION" != "$EXPECTED_RING_VERSION" ] ||
  [ "$RING_CHECKSUM" != "$EXPECTED_RING_CHECKSUM" ]; then
  printf '%s\n' \
    "ring changed from $EXPECTED_RING_VERSION ($EXPECTED_RING_CHECKSUM)." \
    "Found ${RING_VERSION:-missing} (${RING_CHECKSUM:-missing})." \
    'Review its compiled native files and per-file notices, then update about.hbs and this check.' >&2
  exit 1
fi

GENERATED_NOTICE=$(mktemp)
trap 'rm -f -- "$GENERATED_NOTICE"' EXIT HUP INT TERM

cargo about generate \
  --workspace \
  --locked \
  --fail \
  --output-file "$GENERATED_NOTICE" \
  about.hbs

# cargo-about normally follows crate-level metadata, but zstd-sys also compiles
# a separately licensed native implementation. Keep this explicit assertion in
# addition to the byte-for-byte notice comparison so refreshing the generated
# file can never silently remove the required binary-redistribution notice.
for notice in "$GENERATED_NOTICE" THIRD_PARTY_LICENSES.html; do
  for required_text in \
    'For Zstandard software' \
    'Copyright (c) Meta Platforms, Inc. and affiliates. All rights reserved.' \
    'Redistributions in binary form must reproduce the above copyright notice'; do
    if ! grep -Fq "$required_text" "$notice"; then
      printf 'Required vendored Zstandard BSD-3 notice is missing from %s.\n' "$notice" >&2
      exit 1
    fi
  done
  for required_text in \
    'ring 0.17.14 native sources' \
    'Copyright (c) 2019, Google Inc.' \
    'Copyright (c) 2014, Intel Corporation.' \
    'Copyright (c) 2014, Google Inc.'; do
    if ! grep -Fq "$required_text" "$notice"; then
      printf 'Required ring native-source ISC notice is missing from %s.\n' "$notice" >&2
      exit 1
    fi
  done
  for required_text in \
    'Microsoft WebView2 SDK loader 1.0.3650.58' \
    'Copyright (C) Microsoft Corporation. All rights reserved.' \
    'The name of Microsoft Corporation, or the names of its contributors'; do
    if ! grep -Fq "$required_text" "$notice"; then
      printf 'Required Microsoft WebView2 SDK BSD-3 notice is missing from %s.\n' "$notice" >&2
      exit 1
    fi
  done
done

if ! cmp -s THIRD_PARTY_LICENSES.html "$GENERATED_NOTICE"; then
  printf '%s\n' \
    'THIRD_PARTY_LICENSES.html is out of date.' \
    'Regenerate it with:' \
    '  cargo about generate --workspace --locked --fail --output-file THIRD_PARTY_LICENSES.html about.hbs' >&2
  exit 1
fi
